[phases.setup]

nixPkgs = ["nodejs_22"]

[phases.install]

cmd = "pnpm install --frozen-lockfile"

[phases.build]

cmd = "ln -sf ../../packages/backend/convex apps/web/convex && pnpm --filter web build"

[start]

cmd = "ln -sf ../../packages/backend/convex apps/web/convex && pnpm --filter web start"

[variables]

NODE_ENV = "production"
NPM_FLAGS = "--prefix=/"
