server {
  listen 8081;
  server_name localhost;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    # This is the magic for SPAs
    # It tries to find the file requested ($uri), then a directory ($uri/),
    # and if it fails, it falls back to serving /index.html.
    try_files $uri $uri/ /index.html;
  }
}